//! Clean-room detection of protocol facts with *injective instances*.
//!
//! Behaviour characterised entirely from black-box oracle observations of the
//! tamarin-prover web UI ("Fact Symbols with Injective Instances" on the
//! `/main/rules` page); see workspace/BEHAVIOR.md. No tamarin-prover source was
//! consulted.
//!
//! A linear fact tag `t` is injective iff:
//!   (I)  some rule contains `t` in *both* its premises and its conclusions
//!        (a state loop), and
//!   (II) in *every* rule, the multiset of `t`-conclusion first-arguments minus
//!        (by term equality) the multiset of `t`-premise first-arguments is a
//!        sub-multiset of the fresh names generated by that rule's `Fr` premises
//!        — i.e. every newly-created instance carries a distinct freshly
//!        generated name in its first argument.

pub mod ast;

use ast::{Fact, Rule, SortHint, Term, VarSpec};
use std::collections::BTreeSet;

/// A fact tag: the fact symbol name together with its arity. Only linear
/// (non-persistent) tags can be injective.
pub type FactTag = (String, usize);

/// Compute the set of protocol fact tags that have injective instances.
///
/// `rules` are the theory's multiset-rewriting rules (each rule's `premises`
/// and `conclusions` are inspected; `actions`, `variants`, `left_right` and
/// `embedded_restrictions` are irrelevant to the decision). For diff theories
/// the caller supplies the concrete left/right rule set.
pub fn injective_fact_instances(rules: &[Rule]) -> BTreeSet<FactTag> {
    // (I) Candidate tags: linear, arity >= 1, occurring in both premises and
    //     conclusions of one rule.
    let mut candidates: BTreeSet<FactTag> = BTreeSet::new();
    for r in rules {
        let prem_tags: BTreeSet<FactTag> = r
            .premises
            .iter()
            .filter(|f| is_linear_keyed(f))
            .map(tag_of)
            .collect();
        for f in &r.conclusions {
            if is_linear_keyed(f) {
                let t = tag_of(f);
                if prem_tags.contains(&t) {
                    candidates.insert(t);
                }
            }
        }
    }

    // (II) Keep only candidates for which every rule creates new instances
    //      conservatively (net-new first-args are distinct freshly-generated
    //      names).
    candidates
        .into_iter()
        .filter(|t| rules.iter().all(|r| rule_conservative_for(r, t)))
        .collect()
}

/// A fact can carry an injective key only if it is linear and has a first
/// argument.
fn is_linear_keyed(f: &Fact) -> bool {
    !f.persistent && !f.args.is_empty()
}

fn tag_of(f: &Fact) -> FactTag {
    (f.name.clone(), f.args.len())
}

fn has_tag(f: &Fact, t: &FactTag) -> bool {
    !f.persistent && f.name == t.0 && f.args.len() == t.1
}

/// Check condition (II) for tag `t` on a single rule.
fn rule_conservative_for(r: &Rule, t: &FactTag) -> bool {
    // First-argument multisets for tag `t`.
    let prem_keys: Vec<&Term> = r
        .premises
        .iter()
        .filter(|f| has_tag(f, t))
        .map(|f| &f.args[0])
        .collect();
    let conc_keys: Vec<&Term> = r
        .conclusions
        .iter()
        .filter(|f| has_tag(f, t))
        .map(|f| &f.args[0])
        .collect();

    // Fresh names generated by this rule (one per `Fr(v)` premise).
    let mut fresh_pool: Vec<&VarSpec> = r
        .premises
        .iter()
        .filter(|f| is_fresh_fact(f))
        .filter_map(|f| match &f.args[0] {
            Term::Var(v) => Some(v),
            _ => None,
        })
        .collect();

    // net_new = conc_keys minus one matching prem_key each (carried instances).
    let mut prem_pool = prem_keys;
    for c in &conc_keys {
        if let Some(pos) = prem_pool.iter().position(|p| *p == *c) {
            prem_pool.remove(pos); // this conclusion instance was carried through
        } else {
            // Newly created: its first argument must be a distinct fresh name.
            match c {
                Term::Var(v) if v.sort == SortHint::Fresh => {
                    match fresh_pool.iter().position(|fv| **fv == *v) {
                        Some(pos) => {
                            fresh_pool.remove(pos);
                        }
                        None => return false, // fresh-sorted but not Fr-generated (or reused)
                    }
                }
                _ => return false, // first argument is not a freshly generated name
            }
        }
    }
    true
}

/// The built-in `Fr` fact that generates a fresh name.
fn is_fresh_fact(f: &Fact) -> bool {
    !f.persistent && f.name == "Fr" && f.args.len() == 1
}
