//! Byte-parity round-trip tests against captured DOT payloads.
//!
//! A minimal parser for the exact DOT dialect the tamarin web UI emits reads
//! each captured fixture into the crate's own [`Graph`] model; re-serializing
//! with [`graph_clean::dot::to_dot`] must reproduce the original bytes exactly.
//! This validates the payload-format spec (BEHAVIOR.md §2, §3) end to end.

use graph_clean::dot::to_dot;
use graph_clean::model::*;

// ----------------------------------------------------------------------------
// Parser for the captured DOT dialect (test-only ingest).
// ----------------------------------------------------------------------------

/// Merge a plain-node legend that spans several physical lines into one logical
/// line, so every statement is a single element.
fn logical_lines(dot: &str) -> Vec<String> {
    let raw: Vec<&str> = dot.split('\n').collect();
    let mut out: Vec<String> = Vec::new();
    let mut i = 0;
    while i < raw.len() {
        let line = raw[i];
        if line.contains("shape=\"plain\"") && !line.trim_end().ends_with("];") {
            let mut buf = String::from(line);
            i += 1;
            loop {
                buf.push('\n');
                buf.push_str(raw[i]);
                if raw[i].trim_end().ends_with("];") {
                    break;
                }
                i += 1;
            }
            out.push(buf);
            i += 1;
        } else {
            out.push(line.to_string());
            i += 1;
        }
    }
    out
}

fn parse(dot: &str) -> Graph {
    let lines = logical_lines(dot);
    let header = if lines.iter().any(|l| l == "packmode=\"cluster\";") {
        Header::Compact
    } else {
        Header::Simple
    };
    // Body is everything strictly inside the outermost `digraph "G" {` … `}`.
    let mut idx = lines.iter().position(|l| l == "digraph \"G\" {").unwrap() + 1;
    let mut g = Graph::new(header);
    g.body = parse_block(&lines, &mut idx);
    g
}

/// Parse statements until the matching `}` (which it consumes). `idx` points at
/// the first inner line.
fn parse_block(lines: &[String], idx: &mut usize) -> Vec<Stmt> {
    let mut out = Vec::new();
    while *idx < lines.len() {
        let line = lines[*idx].clone();
        let trimmed = line.trim_end();
        if trimmed == "}" {
            *idx += 1;
            return out;
        }
        if trimmed.is_empty() || is_block_attr(trimmed) {
            *idx += 1;
            continue;
        }
        if trimmed.starts_with("subgraph \"cluster_") {
            let label = trimmed
                .trim_start_matches("subgraph \"cluster_")
                .trim_end_matches("\" {")
                .to_string();
            *idx += 1;
            // capture color, then inner nodes
            let color = capture_attr(lines, *idx, "color").unwrap();
            let body = parse_block(lines, idx);
            out.push(Stmt::Cluster(Cluster { label, color, body }));
            continue;
        }
        if trimmed == "{" {
            *idx += 1;
            let rank = capture_attr(lines, *idx, "rank").unwrap();
            let body = parse_block(lines, idx);
            out.push(Stmt::RankBlock(RankBlock { rank, body }));
            continue;
        }
        // node or edge statement (single logical line)
        if line.contains(" -> ") {
            out.push(Stmt::Edge(parse_edge(&line)));
        } else {
            out.push(Stmt::Node(parse_node(&line)));
        }
        *idx += 1;
    }
    out
}

/// True for lines that are block attributes (regenerated by the serializer, so
/// dropped on ingest).
fn is_block_attr(l: &str) -> bool {
    if l.starts_with("node[") || l.starts_with("edge[") {
        return true;
    }
    // key="..."; where key is lowercase — but NOT a node/edge stmt (those have '[').
    if l.contains('[') {
        return false;
    }
    if let Some(eq) = l.find('=') {
        let key = &l[..eq];
        return key.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
            && l.ends_with(';');
    }
    false
}

fn capture_attr(lines: &[String], from: usize, key: &str) -> Option<String> {
    let needle = format!("{}=\"", key);
    for l in &lines[from..] {
        let t = l.trim();
        if t.starts_with(&needle) {
            let rest = &t[needle.len()..];
            return Some(rest.trim_end_matches("\";").trim_end_matches('"').to_string());
        }
        if t == "}" {
            break;
        }
    }
    None
}

fn parse_node(line: &str) -> Node {
    let l = line.trim_end();
    let br = l.find('[').unwrap();
    let id = l[..br].to_string();
    let attrs = &l[br + 1..l.rfind("];").unwrap()];
    if attrs.starts_with("shape=\"record\"") {
        // shape="record",label="…",fillcolor="…",style="filled",fontcolor="…",role="…"
        let label_start = l.find(",label=\"").unwrap() + ",label=\"".len();
        let label_end = l.find("\",fillcolor=\"").unwrap();
        let label = &l[label_start..label_end];
        let fillcolor = extract(l, "fillcolor=\"");
        let fontcolor = extract(l, "fontcolor=\"");
        let role = extract(l, "role=\"");
        Node::record(
            id,
            Record {
                columns: parse_record_label(label),
                fillcolor,
                fontcolor,
                role: Role(role),
            },
        )
    } else if attrs.starts_with("shape=\"plain\"") {
        let start = l.find("label=<").unwrap() + "label=<".len();
        let end = l.rfind(">];").unwrap();
        Node::plain(id, &l[start..end])
    } else {
        // ellipse: label="…",shape="ellipse"[,color="…"]
        let label_start = l.find("label=\"").unwrap() + "label=\"".len();
        let label_end = l.find("\",shape=\"ellipse\"").unwrap();
        let label = l[label_start..label_end].to_string();
        let color = if l.contains(",color=\"") {
            Some(extract(l, ",color=\""))
        } else {
            None
        };
        Node::ellipse(id, Ellipse { label, color })
    }
}

fn extract(l: &str, key: &str) -> String {
    let s = l.find(key).unwrap() + key.len();
    let rest = &l[s..];
    let e = rest.find('"').unwrap();
    rest[..e].to_string()
}

/// `{{<p> t|<p> t}|{<p> t}|…}` → columns of ported cells.
fn parse_record_label(s: &str) -> Vec<Vec<Cell>> {
    let inner = &s[1..s.len() - 1]; // strip outer { }
    split_top(inner, '|')
        .into_iter()
        .map(|group| {
            let g = &group[1..group.len() - 1]; // strip group { }
            split_top(g, '|')
                .into_iter()
                .map(|cell| parse_cell(&cell))
                .collect()
        })
        .collect()
}

fn parse_cell(cell: &str) -> Cell {
    // `<port> text`
    let gt = find_unescaped(cell, '>').unwrap();
    let port = cell[1..gt].to_string();
    let text = cell[gt + 2..].to_string(); // skip "> "
    Cell { port, text }
}

/// Split on `sep` at brace-depth 0, honoring backslash escapes.
fn split_top(s: &str, sep: char) -> Vec<String> {
    let mut parts = Vec::new();
    let mut depth = 0i32;
    let mut cur = String::new();
    let mut esc = false;
    for c in s.chars() {
        if esc {
            cur.push(c);
            esc = false;
            continue;
        }
        match c {
            '\\' => {
                cur.push(c);
                esc = true;
            }
            '{' => {
                depth += 1;
                cur.push(c);
            }
            '}' => {
                depth -= 1;
                cur.push(c);
            }
            _ if c == sep && depth == 0 => {
                parts.push(std::mem::take(&mut cur));
            }
            _ => cur.push(c),
        }
    }
    parts.push(cur);
    parts
}

fn find_unescaped(s: &str, target: char) -> Option<usize> {
    let mut esc = false;
    for (i, c) in s.char_indices() {
        if esc {
            esc = false;
            continue;
        }
        if c == '\\' {
            esc = true;
        } else if c == target {
            return Some(i);
        }
    }
    None
}

fn parse_edge(line: &str) -> Edge {
    let l = line.trim_end().trim_end_matches(';');
    let arrow = l.find(" -> ").unwrap();
    let src = parse_endpoint(&l[..arrow]);
    let rest = &l[arrow + 4..];
    let (dst_str, attrs) = match rest.find('[') {
        Some(b) => (&rest[..b], parse_attrs(&rest[b + 1..rest.rfind(']').unwrap()])),
        None => (rest, Vec::new()),
    };
    Edge {
        src,
        dst: parse_endpoint(dst_str),
        attrs,
    }
}

fn parse_endpoint(s: &str) -> EndPoint {
    match s.find(':') {
        Some(c) => EndPoint::port(s[..c].to_string(), s[c + 1..].to_string()),
        None => EndPoint::node(s.to_string()),
    }
}

fn parse_attrs(s: &str) -> Vec<(String, String)> {
    // k="v",k="v",…
    let mut out = Vec::new();
    for part in s.split("\",") {
        let part = part.trim_end_matches('"');
        if let Some(eq) = part.find("=\"") {
            out.push((part[..eq].to_string(), part[eq + 2..].to_string()));
        }
    }
    out
}

// ----------------------------------------------------------------------------
// Tests
// ----------------------------------------------------------------------------

fn check(name: &str, dot: &str) {
    let g = parse(dot);
    let out = to_dot(&g);
    assert_eq!(out, dot, "byte round-trip mismatch for fixture {name}");
    // The inferred header must match what the fixture actually uses.
    assert_eq!(g.infer_header(), g.header, "header trigger mismatch for {name}");
}

#[test]
fn roundtrip_empty() {
    check("empty", include_str!("fixtures/empty.dot"));
}

#[test]
fn roundtrip_simple_ports() {
    check("simple_ports", include_str!("fixtures/simple_ports.dot"));
}

#[test]
fn roundtrip_simple_abbrev() {
    check("simple_abbrev", include_str!("fixtures/simple_abbrev.dot"));
}

#[test]
fn roundtrip_compact_clusters() {
    check("compact_clusters", include_str!("fixtures/compact_clusters.dot"));
}

#[test]
fn roundtrip_compact_abbrev() {
    check("compact_abbrev", include_str!("fixtures/compact_abbrev.dot"));
}

#[test]
fn roundtrip_multi_abbrev() {
    check("multi_abbrev", include_str!("fixtures/multi_abbrev.dot"));
}

/// Bulk generalization check (off by default). Set `GRAPHCLEAN_CORPUS` to a
/// directory of captured `*.dot` payloads; every one must round-trip byte-exact.
/// Used to measure how general the format model is beyond the 6 committed
/// fixtures; prints a summary and fails if any file mismatches.
#[test]
fn roundtrip_corpus_dir() {
    let Ok(dir) = std::env::var("GRAPHCLEAN_CORPUS") else {
        return;
    };
    let mut total = 0usize;
    let mut ok = 0usize;
    let mut fails: Vec<String> = Vec::new();
    for entry in std::fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("dot") {
            continue;
        }
        let dot = std::fs::read_to_string(&path).unwrap();
        total += 1;
        let out = std::panic::catch_unwind(|| to_dot(&parse(&dot)))
            .unwrap_or_else(|_| String::from("<PANIC>"));
        if out == dot {
            ok += 1;
        } else if fails.len() < 20 {
            fails.push(path.file_name().unwrap().to_string_lossy().into_owned());
        }
    }
    eprintln!("corpus round-trip: {ok}/{total} byte-exact");
    for f in &fails {
        eprintln!("  MISMATCH: {f}");
    }
    assert_eq!(ok, total, "{} of {} payloads failed to round-trip", total - ok, total);
}
